### ISSUE TITLE
NameError: name 'exception' is not defined (File "/app/entrypoint.py", line 124, in perform_job)

### ISSUE THREAD

**Issue by Nov05** [jaimevalero/push-kaggle-dataset#14]
Hi there, 

thank you very much for the code, which can indeed improve the kaggle workflow a lot!

~~however, I am not able to run this workflow action successfully to upload my github repo code as a dataset to Kaggle.~~
instead, I kept running into the following errors. 
**update:**   
👉 I removed the '-' character in the dataset title, and [successfully uploaded the entire github repo as a dataset to kaggle](https://github.com/Nov05/kaggle--feedback-prize-ell/actions/runs/6106653867/job/16572121364). it threw the same error, which stopped the action. however, in this case, it is just a minor issue as long as it uploads files.  
👉 also, the kaggle api returned some helpful information this time.  
`Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.15 / client 1.5.12)`

https://github.com/Nov05/kaggle--feedback-prize-ell/actions/runs/6105480385/job/16569053188    
```
2023-09-07 04:40:18.107 | INFO     | __main__:execute:22 - bashCommand= kaggle datasets status ***/kaggle--feedback-prize-ell
2023-09-07 04:40:18.580 | INFO     | __main__:execute:25 - output=b'403 - Forbidden\n'
2023-09-07 04:40:18.581 | DEBUG    | __main__:execute:26 - error=None
2023-09-07 04:40:18.581 | DEBUG    | __main__:perform_job:103 - result for ***/kaggle--feedback-prize-ell is result=b'403 - Forbidden\n'
2023-09-07 04:40:18.581 | DEBUG    | __main__:perform_job:105 - has_to_create_new_dataset=True
```
I assume I can safely ignore the error message above, cause the dataset hasn't been created in kaggle yet.  

```
2023-09-07 04:40:18.596 | INFO     | __main__:execute:22 - bashCommand=kaggle datasets create --dir-mode tar  --public 
2023-09-07 04:40:18.830 | INFO     | __main__:execute:25 - output=b'The dataset title must be between 6 and 50 characters\n'
2023-09-07 04:40:18.831 | DEBUG    | __main__:execute:26 - error=None
2023-09-07 04:40:18.831 | ERROR    | __main__:<module>:201 - An error has been caught in function '<module>', process 'MainProcess' (1), thread 'MainThread' (140582980443008):
Traceback (most recent call last):

> File "/app/entrypoint.py", line 201, in <module>
    main()
    └ <function main at 0x7fdc056deaf0>

  File "/app/entrypoint.py", line 193, in main
    perform_job()
    └ <function perform_job at 0x7fdc056de4c0>

  File "/app/entrypoint.py", line 124, in perform_job
    logger.info(f"Dataset creation result: {exception}")
    │      └ <function Logger.info at 0x7fdc05932d30>
    └ <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>

NameError: name 'exception' is not defined
```
👉 I checked the code. I think here it oughta be "**result**" rather than "**exception**"?  
https://github.com/jaimevalero/push-kaggle-dataset/blob/v3/entrypoint.py  
File "/app/entrypoint.py", line 124, in perform_job  
```
123    result = execute(f"kaggle datasets create --dir-mode tar {vars}").decode("utf-8")
124    logger.info(f"Dataset creation result: {exception}")
```

I guess I can bypass this code block by creating a dataset manually, then run this action.
but i still hope this action can be updated, for that [kaggle apis are not very friendly](https://colab.research.google.com/drive/1bBLZa1uHV47uTGUSzZZt-bsu7uAvp_Zi).

thank you again for the code!

**Comment by Nov05** [comment]
pull request https://github.com/jaimevalero/push-kaggle-dataset/pull/15 created accordingly

**Comment by jaimevalero** [comment]
Hi @Nov05 .

Thank you for taking the time to inform of the bug, and also submitting a patch.
I am merging the PR.

I would need additional info to reproduce the error. Are you trying to upload an entire github repo as a dataset ?

**Comment by Nov05** [comment]
yes, i was.

**Comment by jaimevalero** [comment]
Created [v3.1](https://github.com/jaimevalero/push-kaggle-dataset/releases/tag/v3.1) release.
